### ISSUE TITLE
Leaving SqlLoginForDataAccess but using a domain account throws an error

### ISSUE THREAD

**Issue by jrudley** [patrickperrone/Sitecore-PowerShell-Installer#14]
The SqlLoginForInstall is a domain account and SqlLoginForDataAccess

 is undefined. You must supply a value for SqlLoginForDataAccess.
The specified combination of accounts will not produce a valid SQL login for data access.
Aborting install: config.xml file has a bad setting.

I tried leaving sqlloginfordataaccess empty or with a domain account ie) domain\user while UseWindowsAuthenticationForSqlDataAccess is set to true
http://pastebin.com/QKD6EdPT my config

**Comment by patrickperrone** [comment]
Great catch! I was able to reproduce this. I'll have a fix shortly.

**Comment by jrudley** [comment]
no problem. I have also added a bunch of logic for pre-req checking of components, etc and will be extending functionality for sql server without needing the smo assemblies in the gac.  This is such a great script and the sitecore community needed it! Will share my fork once finished.

Thanks again,
Jimmy

**Comment by patrickperrone** [comment]
Sounds great, can't wait to see what you have done. :)
