### ISSUE TITLE
update incorrect wording on pre-req check

### ISSUE THREAD

**Issue by jrudley** [patrickperrone/Sitecore-PowerShell-Installer#31]
56     $moduleName = "SQLPS" 
57     if (!(Test-Module $moduleName)) 
58     { 
59         Write-Host "Warning: IIS PowerShell Module ($moduleName) is not installed." -ForegroundColor Red 
60         return $FALSE 
61     } 

You are checking for the sql powershell module, but returning iis powershell module if it is not found. Won't break the script, but user might be confused if they do not have sqlps installed.

**Comment by patrickperrone** [comment]
Whoops! Thanks for catching that! :)
