### ISSUE TITLE
checking for sqlps module when db install is not selected

### ISSUE THREAD

**Issue by jrudley** [patrickperrone/Sitecore-PowerShell-Installer#68]
There are a lot of functions, but I couldn't find a reason why you should fail the pre-req check if sqlps module is not installed. ie) I am installing a CD node, but disabled the DB section of the install config. 

Warning: SQL PowerShell Module (SQLPS) is not installed.
Please satisfy pre-requisites and try again.
Aborting install: No action taken.

**Comment by patrickperrone** [comment]
Hi James, could you provide me your .config file so I can reproduce?

**Comment by jrudley** [comment]
sure, will try and give over the weekend as it is on my other box at work. Thanks

**Comment by jrudley** [comment]
[install.zip](https://github.com/patrickperrone/Sitecore-PowerShell-Installer/files/243375/install.zip)

PS C:\temp> .\install.ps1
Testing script pre-requisites.
Warning: SQL PowerShell Module (SQLPS) is not installed.
Please satisfy pre-requisites and try again.
Aborting install: No action taken.
PS C:\temp>

**Comment by jrudley** [comment]
that same config can be used for the other issue for not having enough iis bindings
