### ISSUE TITLE
When using the script in DSC the database files do not get copied

### ISSUE THREAD

**Issue by drryu** [patrickperrone/Sitecore-PowerShell-Installer#82]
When running the script as a step in DSC, the code in Copy-DatabaseFiles, does not seem to be working.

Output of $childItem.Name displays the filename without extensions. This throws off the code and does not end up creating copies of the web database, nor renaming the analytics db to reporting.

**Comment by patrickperrone** [comment]
This has been resolve through merging the pull request.
