### ISSUE TITLE
Reporting.apikey connectionstring not set, throws exception in heartbeat check

### ISSUE THREAD

**Issue by drryu** [patrickperrone/Sitecore-PowerShell-Installer#84]
For sitecore 8.2 (not sure if this is exclusively for 8.2), there seems to be a connection string for reporting.apikey that is not set by the installer. If this is left blank, it fails the heartbeat check.

Need to make sure that the reporting.apikey connectionstring is commented out if it is not set.

**Comment by patrickperrone** [comment]
I've added support to the installer for setting the reporting.apikey connection string. Unfortunately, even when this value is non-empty it fails the heartbeat check. I suspect this is a problem with the heartbeat page itself.
